### ISSUE TITLE
Updating runtime in for a CSP

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-runtime-core#144]
I have an application running with an old version of the runtime and the runtime browser. To be able to use last stable version, I copied the content of [browser runtime](https://github.com/reTHINK-project/dev-runtime-browser/tree/master/bin), to load first content from the application webserver.
Then I deployed the [core runtime](https://github.com/reTHINK-project/dev-runtime-core/tree/master/dist) in the catalogue. I put the Runtime.js in the Runtime folder, and change the name into sourceCode.js, but what about all the other files?   
Now, it does not work anymore: the authentication procedure fails. It seems to be unable to use the admin GUI.
Also it curiously seems to load twice the runtime from the catalogue, wich is not very convenient, as it is almost 2MB.

I suspect the deployment of the core runtime is not complete but I'd like to know where the problem is.
The application is accessible here:  https://call.rethink.orange-labs.fr

**Comment by pchainho** [comment]
In principle using the most updated version of the Default DB Catalogue would be enough but we have to check if this is actually updated in the docker hub.

I'm also missing some guidelines for the provisioning of the runtime in the catalogue and other objects in general. We should work on this.

I've tried your App (btw, very nice :) ) and I confirm Hyperties are not loaded but there are also no errors.

I don't see the admin icon so I suspect that you have just provisioned the core-runtime but not the browser runtime.

Anyway, I would recommend to use the most updated version from docker hub that will also ensure you are using all other compliant objects from the catalogue including protostubs and hyperties.

**Comment by emmelmann-fokus** [comment]
> In principle using the most updated version of the Default DB Catalogue would be enough but we have to check if this is actually updated in the docker hub.

Yes, the reTHINK-default database is updated on docker automatically:  https://hub.docker.com/r/rethink/catalogue-database-rethinkdefault/builds/

You have docker images tagged for builds based on the master branch as well as on the dev branch.

> I'm also missing some guidelines for the provisioning of the runtime in the catalogue and other objects in general. We should work on this.

Please check the existing documentation:  all catalogue objects are provisioned to the database in the same way:
https://github.com/reTHINK-project/dev-catalogue/blob/master/doc/internals/user_view.md

> Anyway, I would recommend to use the most updated version from docker hub that will also ensure you are using all other compliant objects from the catalogue including protostubs and hyperties.

Yes, please do a ```docker pull``` to assure that you have the newest image.  If you want to be absolutely sure, you should also remove all related docker containers and images (via ```docker rm``` or ```docker rmi```).

If there are additional catalogue-related issues, please create a new one at https://github.com/reTHINK-project/dev-catalogue

Cheers,

Marc

**Comment by sbecot** [comment]
Thanks,
Not sure it is actually a catalogue issue. The provisionning is simple if the database is simple, even if it is true that the default one is not working also, but it may come from the distrib of the browser runtime I have.
One question is how is built the runtime:
eg: https://github.com/reTHINK-project/dev-runtime-core/tree/master/dist : you have 5 javascripts files, including PEP.js, sandbox.js, minibus.js, ReThinkCtx.js, but in the catalogue, there is only one sourceCode.js, that seem to be Runtime.js 
So, there are several options about PEP.js, sandbox.js, minibus.js, ReThinkCtx.js:
 1-> they are included in Runtime.js so they shouldn't appear in the dist folder.
 2-> they are to include in Runtime so there is something to do to transform 5 files into one sourceCode.js .
 3-> they are to be loaded, so how we have to write the process (directly included in the code like rethink.js?). 
 4-> they are not usefull, so they shouldn't appear in the dist folder.
I suspect the option 4 is not the good one...

The application is working on an older version of the browser runtime, which by the way is not accessible in the catalogue, but directly on the url of the site (.well-known/runtime/rethink.js, and core.js), as far as I understood.

**Comment by sbecot** [comment]
Is anybody able to answer this question? It seems that something is missing in the delivery process of a platform.

**Comment by pchainho** [comment]
Yes, we have to improve the documentation:

Only the runtime.js is provisioned in the catague. The other files contain reusable runtime components to be used by other reTHINK components eg the policy enginen (PEP.js) is also used by the MN and the minibus is used by the other runtime implementations ie the browser and the nodejs.

But runtime.js only provides the core runtime. If you want to deploy in the testbed the browser runtime we have to serve additional files from [here](https://github.com/reTHINK-project/dev-runtime-browser/tree/master/bin) which are currently delivered through the toolkit by executing`npm start`

As discussed in Lisbon this is not perfect, and these files should not be served by the toolkit itself but by any HTTP server including from a CDN

**Comment by sbecot** [comment]
Thank you for your answer. It means that my deployment was good. I deployed the browser runtime directly with my application. Then it also means that current browser [browser runtime](https://github.com/reTHINK-project/dev-runtime-browser/tree/master/bin) and [core runtime](https://github.com/reTHINK-project/dev-runtime-core/tree/master/dist) on master branch may not be compatible. I say "may", because switching from former version to new one can imply something on application side.

**Comment by sbecot** [comment]
A comprehensive view of the components to deploy is provided [here](https://github.com/reTHINK-project/specs/tree/master/deployment). I updated it with this information. 
I'll complete it with the docker compose solution proposed by Vitor.

**Comment by pchainho** [comment]
It looks great but I have to look on it more carefully. In the [release notes](https://github.com/reTHINK-project/dev-hyperty-toolkit/releases) you can see the different compatible versions. It seems the master versions from the runtime core and the browser runtime are still in sync since they still have the last releases.

**Comment by sbecot** [comment]
Probably there is something missing in the generation. I tried to re-generate with the gulp task but it doesn't change anything.

At this moment, the code delivered in the dev-runtime-core and dev-runtime-browser are not compatible (0.4.0 and 0.7.1). The test is simple: 
1--> you deploy the core runtime in a catalogue, 
2--> you deploy the [browser runtime](https://github.com/reTHINK-project/dev-runtime-browser/tree/master/bin) on a web server (not a node), 
3--> on a web page you load the rethink.js. At this stage Firefox console is giving some errors, but not Chrome. (You can see the same errors on https://hysmart.rethink.ptinovacao.pt/ ).
4--> you try to load an hyperty: it stops somewhere between the policy engine and the identity GUI, and nothing is loaded.

**Comment by sbecot** [comment]
I finally found the problem thanks to the help of Steffen. The admin GUI was simply hidden in the page so I couldn't see anything.
This is a side effect of passing from the old id module to the admin gui I guess.
